name: wechat-auto-reminder
run-name: ${{ github.actor }} is pushing the wechat messages
on:
  workflow_dispatch:
  schedule:
    - cron: '30 00 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo version
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.15
      - name: Set timezone
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Push wechat messages
        run: |
          python3 main.py
